from django.urls import path

from .views import (
    AuditLogListView,
    FailedAccessView,
    HomePageView,
    ManageUserDetailView,
    ManageUserListView,
    ManageUserUpdateView,
    OrganizationCreateView,
    OrganizationDeleteView,
    OrganizationDetailView,
    OrganizationExportCsvView,
    OrganizationListView,
    OrganizationUpdateView,
    ProfileUpdateView,
    ProfileView,
    ProjectCreateView,
    ProjectDeleteView,
    ProjectDetailView,
    ProjectExportCsvView,
    ProjectListView,
    ProjectUpdateView,
    ProtectedAccessHistoryView,
    SecurityDashboardView,
    SecurityEventListView,
    SignUpView,
    TaskCreateView,
    TaskDeleteView,
    TaskDetailView,
    TaskExportCsvView,
    TaskListView,
    TaskStatusCreateView,
    TaskStatusDeleteView,
    TaskStatusDetailView,
    TaskStatusListView,
    TaskStatusUpdateView,
    TaskUpdateView,
    access_denied_view,
    admin_portal_redirect_view,
    protected_report_view,
    secure_access_view,
)

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("accounts/signup/", SignUpView.as_view(), name="signup"),
    path("accounts/profile/", ProfileView.as_view(), name="profile"),
    path("accounts/profile/update/", ProfileUpdateView.as_view(), name="profile-update"),

    path("organizations/", OrganizationListView.as_view(), name="organization-list"),
    path("organizations/export/csv/", OrganizationExportCsvView.as_view(), name="organization-export-csv"),
    path("organizations/add/", OrganizationCreateView.as_view(), name="organization-add"),
    path("organizations/<int:pk>/", OrganizationDetailView.as_view(), name="organization-detail"),
    path("organizations/<int:pk>/edit/", OrganizationUpdateView.as_view(), name="organization-edit"),
    path("organizations/<int:pk>/delete/", OrganizationDeleteView.as_view(), name="organization-delete"),

    path("projects/", ProjectListView.as_view(), name="project-list"),
    path("projects/export/csv/", ProjectExportCsvView.as_view(), name="project-export-csv"),
    path("projects/add/", ProjectCreateView.as_view(), name="project-add"),
    path("projects/<int:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path("projects/<int:pk>/edit/", ProjectUpdateView.as_view(), name="project-edit"),
    path("projects/<int:pk>/delete/", ProjectDeleteView.as_view(), name="project-delete"),

    path("statuses/", TaskStatusListView.as_view(), name="taskstatus-list"),
    path("statuses/add/", TaskStatusCreateView.as_view(), name="taskstatus-add"),
    path("statuses/<int:pk>/", TaskStatusDetailView.as_view(), name="taskstatus-detail"),
    path("statuses/<int:pk>/edit/", TaskStatusUpdateView.as_view(), name="taskstatus-edit"),
    path("statuses/<int:pk>/delete/", TaskStatusDeleteView.as_view(), name="taskstatus-delete"),

    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/export/csv/", TaskExportCsvView.as_view(), name="task-export-csv"),
    path("tasks/add/", TaskCreateView.as_view(), name="task-add"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/<int:pk>/edit/", TaskUpdateView.as_view(), name="task-edit"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),

    path("security/", SecurityDashboardView.as_view(), name="security-dashboard"),
    path("security/audit-logs/", AuditLogListView.as_view(), name="audit-log-list"),
    path("security/events/", SecurityEventListView.as_view(), name="security-event-list"),
    path("security/failed-access/", FailedAccessView.as_view(), name="failed-access-list"),
    path(
        "security/protected-access-history/",
        ProtectedAccessHistoryView.as_view(),
        name="protected-access-history",
    ),

    path("access-denied/", access_denied_view, name="access-denied"),
    path("admin-portal/", admin_portal_redirect_view, name="admin-portal"),
    path("secure-access/", secure_access_view, name="secure-access"),
    path("protected-report/", protected_report_view, name="protected-report"),

    path("manage-users/", ManageUserListView.as_view(), name="manage-user-list"),
    path("manage-users/<int:pk>/", ManageUserDetailView.as_view(), name="manage-user-detail"),
    path("manage-users/<int:pk>/edit/", ManageUserUpdateView.as_view(), name="manage-user-update"),
]